name: CI/CD

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Start containers
      run: docker-compose -f "./BACK/docker-compose.yaml" up -d --build
      env:
        POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
        POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
        POSTGRES_CONNECTION_STRING: postgresql+psycopg2://${{ secrets.POSTGRES_USER }}:${{ secrets.POSTGRES_PASSWORD }}@host.docker.internal:5432/${{ secrets.POSTGRES_DB }}
        API_TOKEN: ${{ secrets.API_TOKEN }}

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install test dependencies
      run: pip install -r simple_tests/requirements.txt
        
    - name: Run tests
      run: pytest simple_tests/test_api.py
      env:
        API_URL: http://localhost:5000
        API_TOKEN: ${{ secrets.API_TOKEN }}
